"""
Audit V2 resource client — query and export audit events.
"""

from typing import Any, Dict, List, Optional

from ._base import V2Resource


class Audit(V2Resource):
    """Client for ``/v2/audit``."""

    _path_prefix = "/v2/audit"

    def list_events(
        self,
        actor_id: Optional[str] = None,
        action: Optional[str] = None,
        from_: Optional[str] = None,
        to: Optional[str] = None,
        page: int = 0,
        size: int = 50,
        **filters: Any,
    ) -> Dict[str, Any]:
        """Query audit events."""
        params: Dict[str, Any] = {"page": page, "size": size, **filters}
        if actor_id is not None:
            params["actorId"] = actor_id
        if action is not None:
            params["action"] = action
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        return self._request("GET", self._url("/events"), params=params)

    def resource_events(
        self,
        resource_type: str,
        resource_id: str,
        page: int = 0,
        size: int = 50,
    ) -> Dict[str, Any]:
        """Events scoped to a single resource."""
        return self._request(
            "GET",
            self._url(f"/events/{resource_type}/{resource_id}"),
            params={"page": page, "size": size},
        )

    def my_events(self, page: int = 0, size: int = 50) -> Dict[str, Any]:
        """Events generated by the calling principal."""
        return self._request(
            "GET",
            self._url("/events/me"),
            params={"page": page, "size": size},
        )

    def export(
        self,
        format: str = "csv",
        from_: Optional[str] = None,
        to: Optional[str] = None,
    ) -> bytes:
        """Export events as CSV/JSON; returns the raw bytes."""
        params: Dict[str, Any] = {"format": format}
        if from_ is not None:
            params["from"] = from_
        if to is not None:
            params["to"] = to
        return self._request("GET", self._url("/export"), params=params)
